module.exports = [
  { id: "Pos_Fun_0001", input: "oyaage pen eka dhenna puLuvandha?" },
  { id: "Pos_Fun_0002", input: "mata iiyee uNa haedhuna nisaa notes tika livvee naehae." },
  { id: "Pos_Fun_0003", input: "Heta mama library ekata gihillaa, magee project eka complete karanna hithuvaa. iita passee, restaurant ekata gihillaa lunch ekak ganna plan kalaa. puLuvan vuNoth, notes vala printouts ganna hithuvaa. Adha thiyana Teams meeting eke link ekath nadhinita send kalaa. Project eka heta ivara karaganna venavaa. Final exam eka February first week eke thiyana nisaa, paadam karannath thiyanavaa.api haemooma ekathu velaa paadam karamu. " },
  { id: "Pos_Fun_0004", input: "eeyi, mata eeka poddak balanna dhenna.ethakota mata kiyanna puLuvan mona vagee dheyakdha kiyalaa." },
  { id: "Pos_Fun_0005", input: "aayuboovan! obata kohomadha? Mama nam hoDHin. " },
  { id: "Pos_Fun_0006", input: "mama adha gedhara yanna hitiye, haebaeyi vahina nisaa dhaenma yannee naee." },
  { id: "Pos_Fun_0007", input: "Api iiyea trip eka giyaa Kandy valata. Ehe hariyata vaessa. Mama hithuvea naee ochchara traffic ekak thiyeyi kiyala. Api dhaval 12.00  vedhdhi train eke hitiye. loku naendhath api ekkama aavaa. vaessa thibuNath apita trip eka hoDHAtama enjoy karanna puLuvan vuNaa. Kandy town eka vatea tikak aevidhalaa photos tikak gaththaa. Havas vedhdhi api sathutinma aapahu gedhara aavaa." },
  { id: "Pos_Fun_0008", input: "hari hari mama eeka karannam." },
  { id: "Pos_Fun_0009", input: "ee online form ekee NIC ekayi,Name ekayi fill karanna thibbaa.Fill karala submit kalaata passee SMS ekak phone ekata enavaa." },
  { id: "Pos_Fun_0010", input: "api udhee 7.30 ta panthiyata aavaa saha 11.00 ta kaeema kaeevaa." },
  { id: "Pos_Fun_0011", input: "mama haal 5kg k gaththaa." },
  { id: "Pos_Fun_0012", input: "Mee traffic eka nisaa late vuNaa. Magee PC ekee RAM eka madhi. Zoom call eka thiyana gaman  whatsapp call ganna baee. WiFi eketh signal aduyi. URL eka copy karala browser ekee paste karanna. QR code eka scan karalaa payment eka karanna. MP4 video eka download vunaama mata kiyanna." },
  { id: "Pos_Fun_0013", input: "ela machan! api iiyee trip eka Jaffna giyea, siraavata supiri!" },
  { id: "Pos_Fun_0014", input: "karuNaakaralaa mata podi udhavvak karanna puLuvandha? magee garden ekee aluth mal vagayak hitavaganna thiyanavaa. oyaa gaava thiyana mal paela tikak mata dhenna puLuvandha?" },
  { id: "Pos_Fun_0015", input: "adha raee 8.00 ta meeting ekak thiyanavaa.ee nisaa adha vaeda tika kalin ivara karanna oonea." },
  { id: "Pos_Fun_0016", input: "mama ekaGAyi." },
  { id: "Pos_Fun_0017", input: "anathurudhaayakayi!praveesam vanna." },
  { id: "Pos_Fun_0018", input: "mata eekanam karanna baee." },
  { id: "Pos_Fun_0019", input: "mama order karapu item eka avaa.eeka tikak damage velaa.eeka maaru karaganna puLuvannam hoDHAyi.." },
  { id: "Pos_Fun_0020", input: "mata next week ekee school ekee exam ekak thiyanavaa.eekata paadam karanna thiyanavaa." },
  { id: "Pos_Fun_0021", input: "mama degree eka ivara unaata passee business ekak patan gannavaa.business eken earn karanna puLuvan veyi.iita passee mama car ekak gannavaa.Colombo valin geyak gannavaa.Magee aasaavak thiyanavaa music academy ekak patan ganna.eekath mama kohomahari karanavaa.Mage ammatayi thaaththatayi lassana geyakuth aran dhenavaa.Eyaalata car ekakuth aragena dhenavaa." },
  { id: "Pos_Fun_0022", input: "oyaata adha puLuvandha?" },
  { id: "Pos_Fun_0023", input: "mata iiye raee bada ridhuNaa.iita passee maava hospital eke naevaeththuvaa.Doctor maava check karalaa kivvaa mata gastritis kiyalaa.beheth bivvama adu veyi kivvaa.mata rest karanna kivvaa.sathiyakin vage adu veyi kivvaa.labana sathiyee aayeema hambavenna kivvaa.Blood ekakuth check karanna kivvaa." },
  { id: "Pos_Fun_0024", input: "vahaama meeka bonna." },
  { id: "Neg_Fun_0025", input: "eyaa ADA eNnam KIWWA." },
  { id: "Neg_Fun_0026", input: "adha udheeta file submision ekak thiyanavaa neadha? " },
  { id: "Neg_Fun_0027", input: "eyaa iiyee Colombo giyaa saha adha yannee naehae kiyalaa hithanavaa namuth anidhdhaata yanavaa kiyalaa hithaagena inne." },
  { id: "Neg_Fun_0028", input: "please eyaama help karanna." },
  { id: "Neg_Fun_0029", input: "enavaadha!!!?????" },
  { id: "Neg_Fun_0030", input: "matapaankannaoonee" },
  { id: "Neg_Fun_0031", input: "mama yanna hadhannee office ekata kiyalaa mama hithuvaa, mama enavadha maath ekka kiyalaa eyaa aehuvaa. haebaeyi, eyaa iiyee gedhara giyaa kiyalaa mama dhannavaa, apita heta office ekee meeting ekak thiyanavaa.eeka thiyenne heta havasata." },
  { id: "Neg_Fun_0032", input: "pls doc eka submit karanna. " },
  { id: "Neg_Fun_0033", input: "ee class ekee Lamayi fifty hitiyaa aluthin Lamayi 5k gannavaa kivvaa." },
  { id: "Pos_Fun_0025", input: "mama heta gama yanavaa." },
  { id: "Pos_Fun_0026", input: "oyaage nama mokakdha?" },
  { id: "Pos_Fun_0027", input: "mata vathura tikak dhenna." },
  { id: "Pos_Fun_0028", input: "api cricket gahamu." },
  { id: "Pos_Fun_0029", input: "bus eka parakhkhuyi." },
  { id: "Pos_Fun_0030", input: "eliye wahinava." },
  { id: "Neg_Fun_0034", input: "TestNumber123AndSymbol$$$" },
  { id: "Neg_Fun_0035", input: "Inv@lid Ch@rzu." },
  { id: "Pos_UI_0001", input: "mama", description: "UI Test: Check real-time update" }
];
